export const PLAN_LIMITS = {
  starter: {
    name: "Starter",
    price: 999,
    maxUsers: 2,
    maxInvoicesPerMonth: 500,
    maxCustomers: 500,
    maxProducts: 500,
    features: {
      basicReports: true,
      advancedReports: false,
      gstReports: false,
      expenses: true,
      purchaseManagement: true,
      inventory: true,
      paymentTracking: true,
      paymentHistory: false,
      advancedPaymentHistory: false,
      invoiceCustomization: true,
      advancedInvoiceCustomization: false,
      unlimitedInvoiceCustomization: false,
      stockAlerts: true,
      advancedStockAlerts: false,
      enhancedStockMonitoring: false,
      dataExport: false,
    },
  },
  pro: {
    name: "Pro",
    price: 2499,
    maxUsers: 10,
    maxInvoicesPerMonth: Infinity,
    maxCustomers: 5000,
    maxProducts: 5000,
    features: {
      basicReports: true,
      advancedReports: true,
      gstReports: true,
      expenses: true,
      purchaseManagement: true,
      inventory: true,
      paymentTracking: true,
      paymentHistory: true,
      advancedPaymentHistory: false,
      invoiceCustomization: true,
      advancedInvoiceCustomization: true,
      unlimitedInvoiceCustomization: false,
      stockAlerts: true,
      advancedStockAlerts: true,
      enhancedStockMonitoring: false,
      dataExport: true,
    },
  },
  enterprise: {
    name: "Enterprise",
    price: 6999,
    maxUsers: Infinity,
    maxInvoicesPerMonth: Infinity,
    maxCustomers: Infinity,
    maxProducts: Infinity,
    features: {
      basicReports: true,
      advancedReports: true,
      gstReports: true,
      expenses: true,
      purchaseManagement: true,
      inventory: true,
      paymentTracking: true,
      paymentHistory: true,
      advancedPaymentHistory: true,
      invoiceCustomization: true,
      advancedInvoiceCustomization: true,
      unlimitedInvoiceCustomization: true,
      stockAlerts: true,
      advancedStockAlerts: true,
      enhancedStockMonitoring: true,
      dataExport: true,
    },
  },
};
