export const PLAN_LIMITS = {
  starter: {
    name: "Starter",
    price: 999,
    maxBusinesses: 1,
    maxUsers: 2,
    maxInvoicesPerMonth: 500,
    features: {
      basicReports: true,
      emailSupport: true,
      advancedReports: false,
      gstFiling: false,
      prioritySupport: false,
      barcodeScanner: false,
      apiAccess: false,
      customIntegrations: false,
      dedicatedManager: false,
    },
  },
  pro: {
    name: "Pro",
    price: 2499,
    maxBusinesses: 3,
    maxUsers: 10,
    maxInvoicesPerMonth: Infinity,
    features: {
      basicReports: true,
      emailSupport: true,
      advancedReports: true,
      gstFiling: true,
      prioritySupport: true,
      barcodeScanner: true,
      apiAccess: false,
      customIntegrations: false,
      dedicatedManager: false,
    },
  },
  enterprise: {
    name: "Enterprise",
    price: 6999,
    maxBusinesses: Infinity,
    maxUsers: Infinity,
    maxInvoicesPerMonth: Infinity,
    features: {
      basicReports: true,
      emailSupport: true,
      advancedReports: true,
      gstFiling: true,
      prioritySupport: true,
      barcodeScanner: true,
      apiAccess: true,
      customIntegrations: true,
      dedicatedManager: true,
    },
  },
};
