export const PLAN_LIMITS = {
  starter: {
    name: "Starter",
    price: 999,
    maxUsers: 2,
    maxInvoicesPerMonth: 500,
    maxCustomers: 500,
    maxProducts: 500,
    features: {
      basicReports: true,
      advancedReports: false,
      gstReports: false,
      barcodeScanner: false,
      expenses: true,
      purchaseManagement: true,
      inventory: true,
      advancedInventory: false,
      dataExport: false,
      apiAccess: false,
    },
  },
  pro: {
    name: "Pro",
    price: 2499,
    maxUsers: 10,
    maxInvoicesPerMonth: Infinity,
    maxCustomers: 5000,
    maxProducts: 5000,
    features: {
      basicReports: true,
      advancedReports: true,
      gstReports: true,
      barcodeScanner: true,
      expenses: true,
      purchaseManagement: true,
      inventory: true,
      advancedInventory: true,
      dataExport: true,
      apiAccess: false,
    },
  },
  enterprise: {
    name: "Enterprise",
    price: 6999,
    maxUsers: Infinity,
    maxInvoicesPerMonth: Infinity,
    maxCustomers: Infinity,
    maxProducts: Infinity,
    features: {
      basicReports: true,
      advancedReports: true,
      gstReports: true,
      barcodeScanner: true,
      expenses: true,
      purchaseManagement: true,
      inventory: true,
      advancedInventory: true,
      dataExport: true,
      apiAccess: true,
    },
  },
};
